apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: demo-homelab
servers: 1
agents: 3
options:
  k3d:
    wait: true
    timeout: 180s
  k3s:
    extraArgs:
      - arg: "--disable=servicelb"
        nodeFilters:
          - server:0
      - arg: "--disable=traefik"
        nodeFilters:
          - server:0
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
ports:
  - port: 0.0.0.0:8443:443
    nodeFilters:
      - loadbalancer
