apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev-micro-saas
servers: 1
agents: 1
options:
  k3d:
    wait: true
    timeout: 120s
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:0
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
ports:
  - port: 0.0.0.0:8080:80
    nodeFilters:
      - loadbalancer
